### ISSUE TITLE
possible linker error not solved by switching /lib library files

### ISSUE THREAD

**Issue by warrenmcg** [jhhung/Tailor#6]
Hi Jui-Hung Hung,

I’m a graduate student who was introduced to your tool at the RNA Society Meeting last week after your paper was mentioned in a talk by Stefan Ameres. I wanted to try your tool out on a small-RNA-Seq dataset that my lab and collaborators collected.

I still consider myself a novice to bioinformatics, particularly when it comes to C++. I attempted to install Tailor from the github release, following the instructions on the website, and received an error that I cannot interpret.

I’m installing on Ubuntu 14.04.2 with boost and gcc. I tried to use the Linux library file (libabwt_table_LINUX.a) instead of the default file, but I received the same error.

Here is the output from the "make" command:

    /usr/bin/cmake -H/home/warren/Downloads/Tailor-1.0 -B/home/warren/Downloads/Tailor-1.0 --check-build-system CMakeFiles/Makefile.cmake 0
    /usr/bin/cmake -E cmake_progress_start /home/warren/Downloads/Tailor-1.0/CMakeFiles /home/warren/Downloads/Tailor-1.0/CMakeFiles/progress.marks
    make -f CMakeFiles/Makefile2 all
    make[1]: Entering directory `/home/warren/Downloads/Tailor-1.0'
    make -f CMakeFiles/bin/tailor.dir/build.make CMakeFiles/bin/tailor.dir/depend
    make[2]: Entering directory `/home/warren/Downloads/Tailor-1.0'
    cd /home/warren/Downloads/Tailor-1.0 && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/warren/Downloads/Tailor-1.0 /home/warren/Downloads/Tailor-1.0 /home/warren/Downloads/Tailor-1.0 /home/warren/Downloads/Tailor-1.0 /home/warren/Downloads/Tailor-1.0/CMakeFiles/bin/tailor.dir/DependInfo.cmake --color=
    make[2]: Leaving directory `/home/warren/Downloads/Tailor-1.0'
    make -f CMakeFiles/bin/tailor.dir/build.make CMakeFiles/bin/tailor.dir/build
    make[2]: Entering directory `/home/warren/Downloads/Tailor-1.0'
    Linking CXX executable bin/tailor
    /usr/bin/cmake -E cmake_link_script CMakeFiles/bin/tailor.dir/link.txt --verbose=1
    /usr/bin/c++   -Ofast -std=c++11    CMakeFiles/bin/tailor.dir/src/main.cpp.o  -o bin/tailor -rdynamic /usr/local/lib/libboost_date_time.so /usr/local/lib/libboost_filesystem.so /usr/local/lib/libboost_system.so /usr/local/lib/libboost_serialization.so /usr/local/lib/libboost_system.so /usr/local/lib/libboost_filesystem.so /usr/local/lib/libboost_regex.so /usr/local/lib/libboost_thread.so /usr/local/lib/libboost_iostreams.so /usr/local/lib/libboost_program_options.so -lpthread -lz lib/libabwt_table.a /usr/local/lib/libboost_serialization.so /usr/local/lib/libboost_regex.so /usr/local/lib/libboost_thread.so /usr/local/lib/libboost_iostreams.so /usr/local/lib/libboost_program_options.so -lpthread -lz lib/libabwt_table.a -Wl,-rpath,/usr/local/lib 
    lib/libabwt_table.a(abwt_table.o): In function `ABWT_table::readBWT(std::string)':
    abwt_table.cpp:(.text+0xbfd): undefined reference to `boost::archive::detail::shared_ptr_helper::shared_ptr_helper()'
    abwt_table.cpp:(.text+0xc34): undefined reference to `boost::archive::detail::shared_ptr_helper::~shared_ptr_helper()'
    lib/libabwt_table.a(abwt_table.o): In function `ABWT_table::readSEQ(std::string, ABSequence<std::string>&)':
    abwt_table.cpp:(.text+0xd1d): undefined reference to `boost::archive::detail::shared_ptr_helper::shared_ptr_helper()'
    abwt_table.cpp:(.text+0xd53): undefined reference to `boost::archive::detail::shared_ptr_helper::~shared_ptr_helper()'
    lib/libabwt_table.a(abwt_table.o): In function `ABWT_table::createAllTable(ABSequence<std::string>&, std::vector<std::string, std::allocator<std::string> >&)':
    abwt_table.cpp:(.text+0x3e8c): undefined reference to `boost::archive::detail::shared_ptr_helper::shared_ptr_helper()'
    abwt_table.cpp:(.text+0x5824): undefined reference to `boost::archive::detail::shared_ptr_helper::~shared_ptr_helper()'
    lib/libabwt_table.a(abwt_table.o): In function `ABWT_table::readTable(std::string)':
    abwt_table.cpp:(.text+0x5f56): undefined reference to `boost::archive::detail::shared_ptr_helper::shared_ptr_helper()'
    abwt_table.cpp:(.text+0x618f): undefined reference to `boost::archive::detail::shared_ptr_helper::~shared_ptr_helper()'
    lib/libabwt_table.a(abwt_table.o): In function `ABWT_table::readNPosLen(std::string const&)':
    abwt_table.cpp:(.text+0x6c81): undefined reference to `boost::archive::detail::shared_ptr_helper::shared_ptr_helper()'
    abwt_table.cpp:(.text+0x6ccc): undefined reference to `boost::archive::detail::shared_ptr_helper::~shared_ptr_helper()'
    collect2: error: ld returned 1 exit status
    make[2]: *** [bin/tailor] Error 1
    make[2]: Leaving directory `/home/warren/Downloads/Tailor-1.0'
    make[1]: *** [CMakeFiles/bin/tailor.dir/all] Error 2
    make[1]: Leaving directory `/home/warren/Downloads/Tailor-1.0'
    make: *** [all] Error 2

Let me know what can be done to fix this error.

Thanks,
Warren

**Comment by jhhung** [comment]
Dear Warren,

Did you find the binary in the latest release?
and when you install by cmake, did you use the boost environment path?
it seems like cmake did not find your boost library or your boost is outdated.

Best,

Jui-Hung

**Comment by warrenmcg** [comment]
I'm using the source code from the latest release. Is the "tailor_v.1.0_linux_static" the binary? I downloaded that, but it wasn't executable and had no file extension, so I'm not sure its purpose is. Otherwise, I was attempting to install from the source code using your instructions. I also am using the latest version of boost (v. 1.58.0). I did not post the output from the cmake step above (sorry!), but I can show it below:

    -- Boost version: 1.58.0
    -- Boost version: 1.58.0
    -- Found the following Boost libraries:
    --   date_time
    --   filesystem
    --   system
    --   serialization
    --   system
    --   filesystem
    --   regex
    --   thread
    --   iostreams
    --   program_options
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/warren/Downloads/Tailor-1.0

What are the next steps?

**Comment by jhhung** [comment]
Yes it is executable,

Please type:

  chmod +x tailor_v.1.0_linux_static

Let me know.

**Comment by warrenmcg** [comment]
Hi Jui-Hung,

I was able to get the executable to work. It's unfortunate that I was unable to solve the installation from source problem, but I will be able to work with your tool now! Thanks!

**Comment by jhhung** [comment]
Dear Warren,

it is hard for me to help you from this side of the world without knowing
the exact configuration of your system, according to your error
message boost::archive
(serialization) was either not presented in your library path or did not
support the function: shared_ptr_helper::shared_ptr_helper().

Best,

Jui-Hung

**Comment by warrenmcg** [comment]
Dear Jui-Hung,

You are correct. I'm sorry if I came across as impatient or rude.

Following up your suggestion, it appears that my version of boost::archive does not support shared_ptr_helper::shared_ptr_helper() (the .hpp files are not present in the /usr/local/include/boost/archive/ directory). My version has that function in the boost::serialization library (i.e. shared_ptr.hpp and shared_ptr_helper.hpp are in /usr/local/include/boost/serialization/ directory). What version of boost was your code built on? Or alternatively, not being familiar with C++ code, how can I modify the code so that refs to shared_ptr_helper() can point to boost::serialization rather than boost::archive when the code is being built?

Thanks for your patience with me.

**Comment by jhhung** [comment]
Would you please use the default library and just follow the sequence:

cmake ./
make

And paste ALL the message on screen to me? 

Best,

Jui-Hung

**Comment by warrenmcg** [comment]
Hi Jui-Hung,

I apologize for the frustration. Here is the full output (with the two commands) using the default library "Tailor-1.0/lib/libabwt_table.a" on my system (which, if it matters, is Ubuntu 14.04.2):

    ~/Downloads/Tailor-1.0$ sudo cmake .
    
    -- Boost version: 1.58.0
    -- Boost version: 1.58.0
    -- Found the following Boost libraries:
    --   date_time
    --   filesystem
    --   system
    --   serialization
    --   system
    --   filesystem
    --   regex
    --   thread
    --   iostreams
    --   program_options
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/warren/Downloads/Tailor-1.0
    
    ~/Downloads/Tailor-1.0$ sudo make
    
    /usr/bin/cmake -H/home/warren/Downloads/Tailor-1.0 -B/home/warren/Downloads/Tailor-1.0 --check-build-system CMakeFiles/Makefile.cmake 0
    /usr/bin/cmake -E cmake_progress_start /home/warren/Downloads/Tailor-1.0/CMakeFiles /home/warren/Downloads/Tailor-1.0/CMakeFiles/progress.marks
    make -f CMakeFiles/Makefile2 all
    make[1]: Entering directory `/home/warren/Downloads/Tailor-1.0'
    make -f CMakeFiles/bin/tailor.dir/build.make CMakeFiles/bin/tailor.dir/depend
    make[2]: Entering directory `/home/warren/Downloads/Tailor-1.0'
    cd /home/warren/Downloads/Tailor-1.0 && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/warren/Downloads/Tailor-1.0 /home/warren/Downloads/Tailor-1.0 /home/warren/Downloads/Tailor-1.0 /home/warren/Downloads/Tailor-1.0 /home/warren/Downloads/Tailor-1.0/CMakeFiles/bin/tailor.dir/DependInfo.cmake --color=
    Scanning dependencies of target tailor
    make[2]: Leaving directory `/home/warren/Downloads/Tailor-1.0'
    make -f CMakeFiles/bin/tailor.dir/build.make CMakeFiles/bin/tailor.dir/build
    make[2]: Entering directory `/home/warren/Downloads/Tailor-1.0'
    /usr/bin/cmake -E cmake_progress_report /home/warren/Downloads/Tailor-1.0/CMakeFiles 1
    [100%] Building CXX object CMakeFiles/bin/tailor.dir/src/main.cpp.o
    /usr/bin/c++   -DmyALPHABET -Ofast -std=c++11 -I/usr/local/include    -o CMakeFiles/bin/tailor.dir/src/main.cpp.o -c /home/warren/Downloads/Tailor-1.0/src/main.cpp
    Linking CXX executable bin/tailor
    /usr/bin/cmake -E cmake_link_script CMakeFiles/bin/tailor.dir/link.txt --verbose=1
    /usr/bin/c++   -Ofast -std=c++11    CMakeFiles/bin/tailor.dir/src/main.cpp.o  -o bin/tailor -rdynamic /usr/local/lib/libboost_date_time.so /usr/local/lib/libboost_filesystem.so /usr/local/lib/libboost_system.so /usr/local/lib/libboost_serialization.so /usr/local/lib/libboost_system.so /usr/local/lib/libboost_filesystem.so /usr/local/lib/libboost_regex.so /usr/local/lib/libboost_thread.so /usr/local/lib/libboost_iostreams.so /usr/local/lib/libboost_program_options.so -lpthread -lz lib/libabwt_table.a /usr/local/lib/libboost_serialization.so /usr/local/lib/libboost_regex.so /usr/local/lib/libboost_thread.so /usr/local/lib/libboost_iostreams.so /usr/local/lib/libboost_program_options.so -lpthread -lz lib/libabwt_table.a -Wl,-rpath,/usr/local/lib 
    lib/libabwt_table.a(abwt_table.o): In function `ABWT_table::readBWT(std::string)':
        abwt_table.cpp:(.text+0x118d): undefined reference to `boost::archive::detail::shared_ptr_helper::shared_ptr_helper()'
        abwt_table.cpp:(.text+0x11c4): undefined reference to `boost::archive::detail::shared_ptr_helper::~shared_ptr_helper()'
    lib/libabwt_table.a(abwt_table.o): In function `ABWT_table::readSEQ(std::string, ABSequence<std::string>&)':
        abwt_table.cpp:(.text+0x12ad): undefined reference to `boost::archive::detail::shared_ptr_helper::shared_ptr_helper()'
        abwt_table.cpp:(.text+0x12e3): undefined reference to `boost::archive::detail::shared_ptr_helper::~shared_ptr_helper()'
    lib/libabwt_table.a(abwt_table.o): In function `ABWT_table::createAllTable(ABSequence<std::string>&, std::vector<std::string, std::allocator<std::string> >&)':
        abwt_table.cpp:(.text+0x268c): undefined reference to `boost::archive::detail::shared_ptr_helper::shared_ptr_helper()'
        abwt_table.cpp:(.text+0x41ee): undefined reference to `boost::archive::detail::shared_ptr_helper::~shared_ptr_helper()'
    lib/libabwt_table.a(abwt_table.o): In function `ABWT_table::readTable(std::string)':
        abwt_table.cpp:(.text+0x4e76): undefined reference to `boost::archive::detail::shared_ptr_helper::shared_ptr_helper()'
        abwt_table.cpp:(.text+0x50c7): undefined reference to `boost::archive::detail::shared_ptr_helper::~shared_ptr_helper()'
    lib/libabwt_table.a(abwt_table.o): In function `ABWT_table::readNPosLen(std::string const&)':
        abwt_table.cpp:(.text+0x5691): undefined reference to `boost::archive::detail::shared_ptr_helper::shared_ptr_helper()'
        abwt_table.cpp:(.text+0x56dc): undefined reference to `boost::archive::detail::shared_ptr_helper::~shared_ptr_helper()'
    collect2: error: ld returned 1 exit status
    make[2]: *** [bin/tailor] Error 1
    make[2]: Leaving directory `/home/warren/Downloads/Tailor-1.0'
    make[1]: *** [CMakeFiles/bin/tailor.dir/all] Error 2
    make[1]: Leaving directory `/home/warren/Downloads/Tailor-1.0'
    make: *** [all] Error 2
